export const GET_USERS = 'GET_USERS';

export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';

export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

export const ADD_USER = 'ADD_USERS';

export const ADD_USER_SUCCESS = 'ADD_USERS_SUCCESS';

export const ADD_USER_FAILURE = 'ADD_USERS_FAILURE';
