version: '3'

services:
  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: melcaro
      MONGO_INITDB_ROOT_PASSWORD: melcaro
    ports:
      - '27017:27017'

  app:
    build:
      context: .
      dockerfile: ./node.Dockerfile
    volumes:
      - '../:/node/app'

  server:
    build:
      context: .
      dockerfile: ./nginx.Dockerfile
    ports:
      - '8080:80'
    volumes:
      - '../images:/images'
      - '../../client/build:/usr/share/nginx/html/'
